[workspace]
resolver = "2"
members = [
    "pallets/dkim-registry",
    "pallets/zkattest",
]

[workspace.dependencies]
codec = { package = "parity-scale-codec", version = "3.7", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }
frame-support = { version = "=47.0.0", default-features = false }
frame-system = { version = "=47.0.0", default-features = false }
sp-core = { version = "=41.0.0", default-features = false }
sp-runtime = { version = "=47.0.0", default-features = false }
sp-io = { version = "=46.0.0", default-features = false }
sp-std = { version = "=14.0.0", default-features = false }

[profile.release]
panic = "unwind"
